    #[derive(Debug)]
    #[repr(C)]
pub struct Nifti1Header {
    pub sizeof_hdr: i32,
    pub data_type: [u8; 10],
    pub db_name: [u8; 18],
    pub extents: i32,
    pub session_error: i16,
    pub regular: u8,
    pub dim_info: u8,
    pub dim: [i16; 8],
    pub intent_p1: f32,
    pub intent_p2: f32,
    pub intent_p3: f32,
    pub intent_code: i16,
    pub datatype: i16,
    pub bitpix: i16,
    pub slice_start: i16,
    pub pixdim: [f32; 8],
    pub vox_offset: f32,
    pub scl_slope: f32,
    pub scl_inter: f32,
    pub slice_end: i16,
    pub slice_code: u8,
    pub xyzt_units: u8,
    pub cal_max: f32,
    pub cal_min: f32,
    pub slice_duration: f32,
    pub toffset: f32,
    pub glmax: i32,
    pub glmin: i32,
    pub descrip: [u8; 80],
    pub aux_file: [u8; 24],
    pub qform_code: i16,
    pub sform_code: i16,
    pub quatern_b: f32,
    pub quatern_c: f32,
    pub quatern_d: f32,
    pub qoffset_x: f32,
    pub qoffset_y: f32,
    pub qoffset_z: f32,
    pub srow_x: [f32; 4],
    pub srow_y: [f32; 4],
    pub srow_z: [f32; 4],
    pub intent_name: [u8; 16],
    pub magic: [u8; 4],
}

// default Nifti1Header use for debug
impl Default for Nifti1Header {
    fn default() -> Self {
        Nifti1Header {
            sizeof_hdr: 348,
            data_type: [0; 10],
            db_name: [0; 18],
            extents: 0,
            session_error: 0,
            regular: 0,
            dim_info: 0,
            dim: [0; 8],
            intent_p1: 0.0,
            intent_p2: 0.0,
            intent_p3: 0.0,
            intent_code: 0,
            datatype: 0,
            bitpix: 0,
            slice_start: 0,
            pixdim: [0.0; 8],
            vox_offset: 0.0,
            scl_slope: 0.0,
            scl_inter: 0.0,
            slice_end: 0,
            slice_code: 0,
            xyzt_units: 0,
            cal_max: 0.0,
            cal_min: 0.0,
            slice_duration: 0.0,
            toffset: 0.0,
            glmax: 0,
            glmin: 0,
            descrip: [0; 80],
            aux_file: [0; 24],
            qform_code: 0,
            sform_code: 0,
            quatern_b: 0.0,
            quatern_c: 0.0,
            quatern_d: 0.0,
            qoffset_x: 0.0,
            qoffset_y: 0.0,
            qoffset_z: 0.0,
            srow_x: [0.0; 4],
            srow_y: [0.0; 4],
            srow_z: [0.0; 4],
            intent_name: [0; 16],
            magic: *b"n+1\0",
        }
    }
}



pub enum NiftiOffsets {
    SizeOfHdr = 0,
    DataType = 4,
    DbName = 14,
    Extents = 32,
    SessionError = 36,
    Regular = 38,
    DimInfo = 39,
    Dim = 40,
    IntentP1 = 56,
    IntentP2 = 60,
    IntentP3 = 64,
    IntentCode = 68,
    DataTypeCode = 70,
    Bitpix = 72,
    SliceStart = 74,
    Pixdim = 76,
    VoxOffset = 108,
    SclSlope = 112,
    SclInter = 116,
    SliceEnd = 120,
    SliceCode = 122,
    XyztUnits = 123,
    CalMax = 124,
    CalMin = 128,
    SliceDuration = 132,
    TOffset = 136,
    GlMax = 140,
    GlMin = 144,
    Descrip = 148,
    AuxFile = 228,
    QFormCode = 252,
    SFormCode = 254,
    QuaternB = 256,
    QuaternC = 260,
    QuaternD = 264,
    QOffsetX = 268,
    QOffsetY = 272,
    QOffsetZ = 276,
    SRowX = 280,
    SRowY = 296,
    SRowZ = 312,
    IntentName = 328,
    Magic = 344,
}
